/* ================================================================
   PAUD Cemara — Seed data
   News, gallery, programs, teachers, messages, settings
   ================================================================ */

window.SEED = {
  settings: {
    schoolName: "PAUD Cemara",
    tagline_id: "Taman tempat anak belajar menjadi diri sendiri.",
    tagline_en: "A garden where children learn to be themselves.",
    address: "Villa Puncak Tidar N-01, Karangwidoro, Dau, Malang 65151",
    phone: "+62 341 550 175",
    whatsapp: "628112334455",
    email: "halo@paudcemara.id",
    hours_id: "Senin–Jumat · 07.30–13.30",
    hours_en: "Mon–Fri · 07.30–13.30",
    maps_embed_url: "https://www.openstreetmap.org/export/embed.html?bbox=112.575%2C-7.925%2C112.595%2C-7.912&layer=mapnik&marker=-7.9186%2C112.5841",
  },

  stats: [
    { k: "hero_stat1", n: "142" },
    { k: "hero_stat2", n: "18" },
    { k: "hero_stat3", n: "17" },
    { k: "hero_stat4", n: "60+" },
  ],

  programs: [
    {
      id: "kb",
      age_id: "Usia 2–3 tahun",
      age_en: "Ages 2–3",
      title_id: "Kelompok Bermain",
      title_en: "Playgroup",
      tone: "yellow",
      hours_id: "3 jam / hari · 3× seminggu",
      hours_en: "3 hrs / day · 3× weekly",
      desc_id: "Eksplorasi sensorik, musik, dan interaksi pertama dengan teman sebaya.",
      desc_en: "Sensory play, music, and first friendships with peers.",
      pillars_id: ["Bermain bebas", "Lingkaran lagu", "Eksplorasi tekstur"],
      pillars_en: ["Free play", "Song circle", "Texture exploration"],
    },
    {
      id: "tk-a",
      age_id: "Usia 4 tahun",
      age_en: "Age 4",
      title_id: "TK A",
      title_en: "Kindergarten A",
      tone: "green",
      hours_id: "5 jam / hari · 5× seminggu",
      hours_en: "5 hrs / day · 5× weekly",
      desc_id: "Literasi awal, numerasi bermakna, dan proyek tematik per dua minggu.",
      desc_en: "Early literacy, meaningful numeracy, and fortnightly thematic projects.",
      pillars_id: ["Membaca bersama", "Numerasi lewat cerita", "Proyek tematik"],
      pillars_en: ["Shared reading", "Math through stories", "Thematic projects"],
    },
    {
      id: "tk-b",
      age_id: "Usia 5–6 tahun",
      age_en: "Ages 5–6",
      title_id: "TK B",
      title_en: "Kindergarten B",
      tone: "blue",
      hours_id: "5 jam / hari · 5× seminggu",
      hours_en: "5 hrs / day · 5× weekly",
      desc_id: "Persiapan SD yang lembut — tetap bermain, tetap bertanya, tanpa terburu-buru.",
      desc_en: "Gentle primary-school prep — still playing, still asking, never rushed.",
      pillars_id: ["Menulis cerita sendiri", "Sains anak", "Proyek komunitas"],
      pillars_en: ["Write-your-own stories", "Kid science", "Community projects"],
    },
  ],

  albums: [
    { id: "all", name_id: "Semua", name_en: "All" },
    { id: "kelas", name_id: "Kegiatan Kelas", name_en: "Classroom", tone: "red" },
    { id: "puncak", name_id: "Puncak Tema", name_en: "Theme Days", tone: "yellow" },
    { id: "ortu", name_id: "Hari Orang Tua", name_en: "Parent Days", tone: "green" },
    { id: "kebun", name_id: "Kebun Sekolah", name_en: "School Garden", tone: "blue" },
    { id: "lulus", name_id: "Kelulusan", name_en: "Graduation", tone: "purple" },
  ],

  gallery: [
    { id: 1, album: "kelas",  caption_id: "Lingkaran pagi di kelas TK A", caption_en: "Morning circle, TK A",          w: 2, h: 2, tone: "yellow" },
    { id: 2, album: "kebun",  caption_id: "Panen tomat ceri pertama",    caption_en: "First cherry tomato harvest",   w: 1, h: 1, tone: "green" },
    { id: 3, album: "puncak", caption_id: "Parade tema profesi",          caption_en: "Careers theme parade",          w: 1, h: 2, tone: "red" },
    { id: 4, album: "ortu",   caption_id: "Ayah membacakan dongeng",      caption_en: "Dad reads a story",             w: 2, h: 1, tone: "blue" },
    { id: 5, album: "kelas",  caption_id: "Kolase daun dari taman",       caption_en: "Leaf collage from the garden",  w: 1, h: 1, tone: "purple" },
    { id: 6, album: "lulus",  caption_id: "Toga kecil kelas TK B",         caption_en: "Tiny toga, class TK B",         w: 1, h: 1, tone: "pink" },
    { id: 7, album: "puncak", caption_id: "Hari air & pelangi",            caption_en: "Water & rainbow day",           w: 1, h: 1, tone: "blue" },
    { id: 8, album: "kebun",  caption_id: "Menanam kangkung bersama",      caption_en: "Planting water spinach",         w: 2, h: 1, tone: "green" },
    { id: 9, album: "kelas",  caption_id: "Eksperimen warna dari kol ungu",caption_en: "Color experiment — red cabbage", w: 1, h: 1, tone: "purple" },
    { id: 10,album: "ortu",   caption_id: "Ibu mengajar membatik",         caption_en: "Mom teaches batik",              w: 1, h: 2, tone: "orange" },
    { id: 11,album: "puncak", caption_id: "Hari pasar tradisional",        caption_en: "Traditional market day",         w: 1, h: 1, tone: "red" },
    { id: 12,album: "kelas",  caption_id: "Cerita sebelum tidur siang",    caption_en: "Story before afternoon nap",     w: 1, h: 1, tone: "yellow" },
  ],

  news: [
    {
      id: "n001",
      slug: "ppdb-2026-dibuka",
      category_id: "Pengumuman",
      category_en: "Announcement",
      tone: "red",
      pinned: true,
      date: "2026-04-21",
      author: "Tim Admin",
      title_id: "PPDB 2026/2027 resmi dibuka — gelombang pertama hingga 30 Mei",
      title_en: "Admissions 2026/2027 now open — first wave until May 30",
      excerpt_id: "Gelombang pertama PPDB PAUD Cemara telah dibuka dengan kuota 36 anak untuk tiga jenjang. Daftar lebih awal, dapat diskon formulir.",
      excerpt_en: "The first admissions wave is open with 36 seats across three levels. Apply early for a form-fee discount.",
      body_id: [
        "Tahun ajaran 2026/2027 akan menjadi tahun ke-18 PAUD Cemara. Kami membuka pendaftaran dalam dua gelombang, dan gelombang pertama resmi dibuka hari ini, 21 April 2026.",
        "Kuota terbatas: 12 anak per jenjang untuk Kelompok Bermain, TK A, dan TK B. Pendaftar gelombang pertama mendapatkan potongan biaya formulir sebesar 30% dan prioritas jadwal observasi.",
        "Alur pendaftaran sama dengan tahun sebelumnya — isi formulir online, kunjungan sekolah, observasi anak (bermain bersama, bukan tes), lalu pengumuman dalam 7 hari kerja.",
        "Butuh info lebih lanjut? Hubungi kami via WhatsApp di nomor yang tertera, atau datang langsung ke kantor Selasa dan Kamis pukul 09.00–11.00.",
      ],
      body_en: [
        "The 2026/2027 academic year will be Cemara's 18th. We open admissions in two waves, and the first wave starts today, April 21, 2026.",
        "Limited seats: 12 children per level across Playgroup, Kindergarten A, and Kindergarten B. First-wave applicants receive a 30% form-fee discount and priority observation scheduling.",
        "The process is the same as last year — fill the online form, school visit, child observation (playing together, not a test), then announcement within 7 business days.",
        "Questions? WhatsApp us at the number listed, or visit the office Tuesdays and Thursdays 09.00–11.00.",
      ],
    },
    {
      id: "n002",
      slug: "panen-kebun",
      category_id: "Cerita Kelas",
      category_en: "Classroom Story",
      tone: "green",
      date: "2026-04-14",
      author: "Bu Ratih",
      title_id: "Panen pertama kebun mini — tomat ceri dan kangkung",
      title_en: "First mini-garden harvest — cherry tomatoes and water spinach",
      excerpt_id: "Tiga bulan menanam, hari ini anak-anak memanen hasilnya dan membawa pulang satu kantung masing-masing.",
      excerpt_en: "Three months of planting, and today the children harvested their first batch and took home a bag each.",
      body_id: [
        "Proyek kebun mini dimulai Januari lalu sebagai bagian dari tema 'Tumbuh bersama tanah'. Setiap kelompok TK A mengadopsi satu petak 1×1 meter.",
        "Hari ini, hasil panen pertama tiba. Tomat ceri, kangkung, dan dua batang daun bawang yang menurut Rania 'tumbuh paling semangat'.",
        "Anak-anak membawa pulang hasil panen dalam kantung kertas daur ulang buatan kelas mereka sendiri. Beberapa orang tua sudah mengirim foto sup kangkung dari rumah.",
      ],
      body_en: [
        "The mini-garden project started last January as part of the 'Growing with the soil' theme. Each TK A group adopted a 1×1 meter plot.",
        "Today the first harvest arrived. Cherry tomatoes, water spinach, and two stalks of spring onion that Rania insists 'grew the most enthusiastically'.",
        "The children took their produce home in recycled paper bags they made themselves. A few parents have already sent photos of spinach soup from home.",
      ],
    },
    {
      id: "n003",
      slug: "libur-idulfitri",
      category_id: "Pengumuman",
      category_en: "Announcement",
      tone: "yellow",
      date: "2026-04-08",
      author: "Tim Admin",
      title_id: "Libur Idulfitri 1447 H: 18 April – 25 April 2026",
      title_en: "Eid holidays 1447 H: April 18–25, 2026",
      excerpt_id: "Sekolah libur selama delapan hari. Kegiatan reguler kembali dimulai Senin, 27 April 2026.",
      excerpt_en: "The school will be closed for eight days. Regular classes resume Monday, April 27, 2026.",
      body_id: [
        "Keluarga besar PAUD Cemara mengucapkan Selamat Idulfitri 1447 H. Mohon maaf lahir dan batin dari tim guru dan staf.",
        "Libur berlangsung dari 18 April sampai 25 April 2026. Kami kembali beraktivitas pada Senin, 27 April, dengan tema baru 'Rumah yang hangat'.",
      ],
      body_en: [
        "The PAUD Cemara family wishes you a joyful Eid 1447 H.",
        "The holiday runs April 18 to 25, 2026. We return to regular schedule on Monday, April 27, with a new theme 'A warm home'.",
      ],
    },
    {
      id: "n004",
      slug: "workshop-montessori",
      category_id: "Acara",
      category_en: "Event",
      tone: "blue",
      date: "2026-03-28",
      author: "Pak Danu",
      title_id: "Workshop orang tua: Mengenali tantrum tanpa panik",
      title_en: "Parent workshop: Handling tantrums without panic",
      excerpt_id: "Sabtu 5 April, bersama psikolog anak Dr. Melati S., kami akan berbagi pendekatan yang ramah anak dan ramah orang tua.",
      excerpt_en: "Saturday April 5, with child psychologist Dr. Melati S., we'll share an approach that's kind to both children and parents.",
      body_id: [
        "Workshop dibuka untuk orang tua PAUD Cemara dan umum. Kapasitas 40 peserta, pendaftaran melalui formulir di halaman kontak.",
        "Sesi berlangsung 09.00–11.30 di aula Cemara, diikuti sesi tanya-jawab dan kopi.",
      ],
      body_en: [
        "The workshop is open to Cemara parents and the public. Capacity 40, register via the form on the contact page.",
        "The session runs 09.00–11.30 in the Cemara hall, followed by Q&A and coffee.",
      ],
    },
    {
      id: "n005",
      slug: "guru-baru-bu-sari",
      category_id: "Sekolah",
      category_en: "School",
      tone: "purple",
      date: "2026-03-15",
      author: "Tim Admin",
      title_id: "Selamat datang, Bu Sari — wali kelas baru TK A-2",
      title_en: "Welcome, Bu Sari — new TK A-2 homeroom teacher",
      excerpt_id: "Dengan 9 tahun pengalaman di PAUD berbasis alam, Bu Sari bergabung bulan ini menggantikan Bu Rini yang pindah tugas.",
      excerpt_en: "With 9 years of nature-based early-education experience, Bu Sari joins us this month, replacing Bu Rini who relocated.",
      body_id: [
        "Bu Sari lulusan PAUD UPI dan sebelumnya mengajar di sekolah alam di Lembang selama hampir satu dekade. Anak-anak TK A-2 sudah mulai bertukar gambar dengan beliau sejak minggu lalu.",
      ],
      body_en: [
        "Bu Sari graduated in Early Childhood Education from UPI and previously taught at a nature school in Lembang for nearly a decade. TK A-2 children have been exchanging drawings with her since last week.",
      ],
    },
    {
      id: "n006",
      slug: "hari-kartini",
      category_id: "Acara",
      category_en: "Event",
      tone: "red",
      date: "2026-04-19",
      author: "Bu Maya",
      title_id: "Hari Kartini: anak-anak cerita tentang perempuan hebat di rumahnya",
      title_en: "Kartini Day: children talk about the heroes at home",
      excerpt_id: "Setiap anak membawa satu foto perempuan yang ia kagumi dari keluarganya dan menceritakannya di depan kelas.",
      excerpt_en: "Each child brought a photo of a woman they admire from their family and shared her story with the class.",
      body_id: [
        "Cerita paling ramai datang dari Bima yang memperkenalkan 'Nenek Kartini', nenek buyutnya yang katanya 'pernah naik kuda sampai Subang'. Kami tidak membantah.",
      ],
      body_en: [
        "The liveliest story came from Bima, introducing 'Grandma Kartini' — his great-grandmother who allegedly 'rode a horse all the way to Subang'. We didn't argue.",
      ],
    },
  ],

  teachers: [
    { id: "t1", name: "Bu Maya Rahardian",    role_id: "Kepala Sekolah",        role_en: "Head of School",         tone: "red" },
    { id: "t2", name: "Pak Danu Syahputra",   role_id: "Koordinator Kurikulum", role_en: "Curriculum Lead",        tone: "blue" },
    { id: "t3", name: "Bu Ratih Kusumastuti", role_id: "Wali Kelas TK A-1",     role_en: "Homeroom TK A-1",        tone: "green" },
    { id: "t4", name: "Bu Sari Indrawati",    role_id: "Wali Kelas TK A-2",     role_en: "Homeroom TK A-2",        tone: "yellow" },
    { id: "t5", name: "Pak Agung Prasetya",   role_id: "Wali Kelas TK B",        role_en: "Homeroom TK B",          tone: "purple" },
    { id: "t6", name: "Bu Lila Ardhana",      role_id: "Guru Musik & Gerak",     role_en: "Music & Movement",       tone: "pink" },
  ],

  messages: [
    { id: "m1", name: "Dewi Anggraini",  email: "dewi@example.id",  subject_id: "Tanya jadwal tur sekolah", subject_en: "Asking about the school tour", preview_id: "Halo, saya ingin tahu apakah masih ada slot tur di minggu kedua Mei…", preview_en: "Hi, I'd like to know if there are still tour slots in the second week of May…", date: "2026-04-22", unread: true },
    { id: "m2", name: "Bapak Hendra P.", email: "hendra.p@example.com", subject_id: "Biaya gelombang kedua",   subject_en: "Second-wave fee",             preview_id: "Apakah ada perubahan biaya antara gelombang 1 dan 2? Terima kasih.", preview_en: "Is there any fee difference between waves 1 and 2? Thank you.", date: "2026-04-21", unread: true },
    { id: "m3", name: "Maria Ulfa",       email: "maria@example.id", subject_id: "Mutasi dari PAUD lain",       subject_en: "Transfer from another school", preview_id: "Anak saya saat ini kelas TK A di Jakarta, kami pindah ke Malang bulan…", preview_en: "My child is currently in TK A in Jakarta, we're moving to Malang next month…", date: "2026-04-18", unread: false },
    { id: "m4", name: "Rachmat S.",       email: "rachmat@example.com", subject_id: "Workshop orang tua",       subject_en: "Parent workshop",             preview_id: "Apakah workshop 5 April masih menerima peserta dari umum?",        preview_en: "Is the April 5 workshop still open to the public?", date: "2026-04-11", unread: false },
  ],

  facilities: [
    { tone: "green",  id: "Kebun mini & area panen",      en: "Mini-garden & harvest plot" },
    { tone: "blue",   id: "Kolam pasir & air",             en: "Sand & water pool" },
    { tone: "red",    id: "Aula musik dan gerak",           en: "Music & movement hall" },
    { tone: "yellow", id: "Perpustakaan anak",              en: "Children's library" },
    { tone: "purple", id: "Dapur belajar (cooking class)",  en: "Learning kitchen" },
    { tone: "orange", id: "Taman bermain luar",             en: "Outdoor playground" },
  ],

  history: [
    { year: "2008", id: "Tiga guru dan sembilan anak memulai kelas di garasi rumah Bu Maya.", en: "Three teachers and nine children start class in Bu Maya's garage." },
    { year: "2012", id: "Pindah ke bangunan di Jalan Cemara Asri — namanya kami pakai sampai sekarang.", en: "We move to a building on Jalan Cemara Asri — the name we still carry today." },
    { year: "2017", id: "Menambahkan jenjang Kelompok Bermain untuk usia 2–3 tahun.", en: "We add a Playgroup level for ages 2–3." },
    { year: "2021", id: "Memulai program kebun mini dan dapur belajar.", en: "We launch the mini-garden and learning-kitchen programs." },
    { year: "2024", id: "Akreditasi A dari BAN-PAUD dan PNF.", en: "Accreditation grade A from BAN-PAUD dan PNF." },
  ],

  fees: [
    { label_id: "Formulir pendaftaran",          label_en: "Application form fee", amount: 150000, once: true },
    { label_id: "Uang pangkal (sekali bayar)",   label_en: "Enrollment fee (one-time)", amount: 6500000, once: true },
    { label_id: "SPP bulanan",                    label_en: "Monthly tuition",       amount: 1250000, once: false },
    { label_id: "Seragam & buku tahunan",         label_en: "Uniform & annual book",  amount: 950000, once: true },
  ],

  // A day at Cemara — 5 time slots
  daySchedule: [
    { time: "07.30", tone: "yellow", id: "Penyambutan & main bebas", en: "Welcome & free play" },
    { time: "08.30", tone: "red",    id: "Lingkaran pagi & lagu",     en: "Morning circle & songs" },
    { time: "09.30", tone: "green",  id: "Proyek tematik / kebun",    en: "Thematic project / garden" },
    { time: "11.00", tone: "blue",   id: "Makan bersama & istirahat", en: "Shared meal & rest" },
    { time: "12.30", tone: "purple", id: "Membaca & lagu pulang",     en: "Reading & farewell song" },
  ],
};
